
###
GET http://localhost:8081/api/teachers/w/courses/

###
DELETE http://localhost:8081/api/courses/10

###
PATCH http://localhost:8081/api/teachers/1/students/2017214317/

###
GET http://localhost:8081/api/courses/


###

DELETE  http://localhost:8081/api/teachers/courses/1

###

PATCH http://localhost:8081/api/teachers/courses/3/name/iio/credit/12

###
GET http://localhost:8081/api/teachers/welcome
Authorization: {{token}}

###
PATCH http://localhost:8081/api/teachers/courses/setting
Authorization: {{token}}
Content-Type: application/json

{
"id":1
}

###
POST http://localhost:8081/api/login
Content-Type: application/json

{
  "number": "1001",
  "password": "1001"
}

> {% client.global.set("token",response.headers.valueOf("Authorization")); %}

###

